const constants = {
  CHUNK_RESOLUTION: 64,
  MIN_CHUNK_SIZE: 8,
  CHUNK_SPLIT_DISTANCE: 1.25,
  OVERSAMPLE_CHUNK_TEXTURES: true,
  ENABLE_TERRAIN_CHUNK_RESOURCE_POOL: true,
  TERRAIN_CHUNK_POOL_SIZE_MIN: 10,
  TERRAIN_CHUNK_POOL_SIZE_LOOKBACK: 100,
  MAX_ASTEROID_RADIUS: 376000,
  AU: 1.495978707e11,
};

export default constants;
